from oneapm/docker-oneapm-ci-agent:latest
add oneapm-ci-agent.conf /etc/cloudinsight-agent/cloudinsight-agent.conf
add nginx.yaml /conf.d/nginx.yaml
add mysql.yaml /conf.d/mysql.yaml
add redisdb.yaml /conf.d/redisdb.yaml